/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HegemonyRouteImport } from './routes/hegemony'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as TSlugRouteImport } from './routes/t.$slug'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as AdminStructureRouteImport } from './routes/admin.structure'
import { Route as AdminSignalsRouteImport } from './routes/admin.signals'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminLessonsRouteImport } from './routes/admin.lessons'
import { Route as AdminDepositsRouteImport } from './routes/admin.deposits'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AppUnlocksRouteImport } from './routes/_app.unlocks'
import { Route as AppToolsRouteImport } from './routes/_app.tools'
import { Route as AppTierRouteImport } from './routes/_app.tier'
import { Route as AppSignalsRouteImport } from './routes/_app.signals'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppLessonsRouteImport } from './routes/_app.lessons'
import { Route as AppLessonsIndexRouteImport } from './routes/_app.lessons.index'
import { Route as AppLessonsLessonIdRouteImport } from './routes/_app.lessons.$lessonId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HegemonyRoute = HegemonyRouteImport.update({
  id: '/hegemony',
  path: '/hegemony',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStructureRoute = AdminStructureRouteImport.update({
  id: '/structure',
  path: '/structure',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSignalsRoute = AdminSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLessonsRoute = AdminLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepositsRoute = AdminDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AppUnlocksRoute = AppUnlocksRouteImport.update({
  id: '/unlocks',
  path: '/unlocks',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsRoute = AppToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AppRoute,
} as any)
const AppTierRoute = AppTierRouteImport.update({
  id: '/tier',
  path: '/tier',
  getParentRoute: () => AppRoute,
} as any)
const AppSignalsRoute = AppSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLessonsRoute = AppLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AppRoute,
} as any)
const AppLessonsIndexRoute = AppLessonsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLessonsRoute,
} as any)
const AppLessonsLessonIdRoute = AppLessonsLessonIdRouteImport.update({
  id: '/$lessonId',
  path: '/$lessonId',
  getParentRoute: () => AppLessonsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/hegemony': typeof HegemonyRoute
  '/login': typeof LoginRoute
  '/lessons': typeof AppLessonsRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/settings': typeof AppSettingsRoute
  '/signals': typeof AppSignalsRoute
  '/tier': typeof AppTierRoute
  '/tools': typeof AppToolsRoute
  '/unlocks': typeof AppUnlocksRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/signals': typeof AdminSignalsRoute
  '/admin/structure': typeof AdminStructureRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/t/$slug': typeof TSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/lessons/$lessonId': typeof AppLessonsLessonIdRoute
  '/lessons/': typeof AppLessonsIndexRoute
}
export interface FileRoutesByTo {
  '/hegemony': typeof HegemonyRoute
  '/login': typeof LoginRoute
  '/notifications': typeof AppNotificationsRoute
  '/settings': typeof AppSettingsRoute
  '/signals': typeof AppSignalsRoute
  '/tier': typeof AppTierRoute
  '/tools': typeof AppToolsRoute
  '/unlocks': typeof AppUnlocksRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/signals': typeof AdminSignalsRoute
  '/admin/structure': typeof AdminStructureRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/t/$slug': typeof TSlugRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/lessons/$lessonId': typeof AppLessonsLessonIdRoute
  '/lessons': typeof AppLessonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/hegemony': typeof HegemonyRoute
  '/login': typeof LoginRoute
  '/_app/lessons': typeof AppLessonsRouteWithChildren
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/signals': typeof AppSignalsRoute
  '/_app/tier': typeof AppTierRoute
  '/_app/tools': typeof AppToolsRoute
  '/_app/unlocks': typeof AppUnlocksRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/signals': typeof AdminSignalsRoute
  '/admin/structure': typeof AdminStructureRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/t/$slug': typeof TSlugRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/lessons/$lessonId': typeof AppLessonsLessonIdRoute
  '/_app/lessons/': typeof AppLessonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/hegemony'
    | '/login'
    | '/lessons'
    | '/notifications'
    | '/settings'
    | '/signals'
    | '/tier'
    | '/tools'
    | '/unlocks'
    | '/admin/audit'
    | '/admin/deposits'
    | '/admin/lessons'
    | '/admin/members'
    | '/admin/signals'
    | '/admin/structure'
    | '/admin/tenants'
    | '/t/$slug'
    | '/admin/'
    | '/lessons/$lessonId'
    | '/lessons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/hegemony'
    | '/login'
    | '/notifications'
    | '/settings'
    | '/signals'
    | '/tier'
    | '/tools'
    | '/unlocks'
    | '/admin/audit'
    | '/admin/deposits'
    | '/admin/lessons'
    | '/admin/members'
    | '/admin/signals'
    | '/admin/structure'
    | '/admin/tenants'
    | '/t/$slug'
    | '/'
    | '/admin'
    | '/lessons/$lessonId'
    | '/lessons'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/hegemony'
    | '/login'
    | '/_app/lessons'
    | '/_app/notifications'
    | '/_app/settings'
    | '/_app/signals'
    | '/_app/tier'
    | '/_app/tools'
    | '/_app/unlocks'
    | '/admin/audit'
    | '/admin/deposits'
    | '/admin/lessons'
    | '/admin/members'
    | '/admin/signals'
    | '/admin/structure'
    | '/admin/tenants'
    | '/t/$slug'
    | '/_app/'
    | '/admin/'
    | '/_app/lessons/$lessonId'
    | '/_app/lessons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  HegemonyRoute: typeof HegemonyRoute
  LoginRoute: typeof LoginRoute
  TSlugRoute: typeof TSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hegemony': {
      id: '/hegemony'
      path: '/hegemony'
      fullPath: '/hegemony'
      preLoaderRoute: typeof HegemonyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/structure': {
      id: '/admin/structure'
      path: '/structure'
      fullPath: '/admin/structure'
      preLoaderRoute: typeof AdminStructureRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/signals': {
      id: '/admin/signals'
      path: '/signals'
      fullPath: '/admin/signals'
      preLoaderRoute: typeof AdminSignalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lessons': {
      id: '/admin/lessons'
      path: '/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof AdminLessonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deposits': {
      id: '/admin/deposits'
      path: '/deposits'
      fullPath: '/admin/deposits'
      preLoaderRoute: typeof AdminDepositsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/unlocks': {
      id: '/_app/unlocks'
      path: '/unlocks'
      fullPath: '/unlocks'
      preLoaderRoute: typeof AppUnlocksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools': {
      id: '/_app/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AppToolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tier': {
      id: '/_app/tier'
      path: '/tier'
      fullPath: '/tier'
      preLoaderRoute: typeof AppTierRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/signals': {
      id: '/_app/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof AppSignalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lessons': {
      id: '/_app/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof AppLessonsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lessons/': {
      id: '/_app/lessons/'
      path: '/'
      fullPath: '/lessons/'
      preLoaderRoute: typeof AppLessonsIndexRouteImport
      parentRoute: typeof AppLessonsRoute
    }
    '/_app/lessons/$lessonId': {
      id: '/_app/lessons/$lessonId'
      path: '/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof AppLessonsLessonIdRouteImport
      parentRoute: typeof AppLessonsRoute
    }
  }
}

interface AppLessonsRouteChildren {
  AppLessonsLessonIdRoute: typeof AppLessonsLessonIdRoute
  AppLessonsIndexRoute: typeof AppLessonsIndexRoute
}

const AppLessonsRouteChildren: AppLessonsRouteChildren = {
  AppLessonsLessonIdRoute: AppLessonsLessonIdRoute,
  AppLessonsIndexRoute: AppLessonsIndexRoute,
}

const AppLessonsRouteWithChildren = AppLessonsRoute._addFileChildren(
  AppLessonsRouteChildren,
)

interface AppRouteChildren {
  AppLessonsRoute: typeof AppLessonsRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSignalsRoute: typeof AppSignalsRoute
  AppTierRoute: typeof AppTierRoute
  AppToolsRoute: typeof AppToolsRoute
  AppUnlocksRoute: typeof AppUnlocksRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLessonsRoute: AppLessonsRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSignalsRoute: AppSignalsRoute,
  AppTierRoute: AppTierRoute,
  AppToolsRoute: AppToolsRoute,
  AppUnlocksRoute: AppUnlocksRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDepositsRoute: typeof AdminDepositsRoute
  AdminLessonsRoute: typeof AdminLessonsRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminSignalsRoute: typeof AdminSignalsRoute
  AdminStructureRoute: typeof AdminStructureRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminDepositsRoute: AdminDepositsRoute,
  AdminLessonsRoute: AdminLessonsRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminSignalsRoute: AdminSignalsRoute,
  AdminStructureRoute: AdminStructureRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  HegemonyRoute: HegemonyRoute,
  LoginRoute: LoginRoute,
  TSlugRoute: TSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
