/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as HegemonyRouteImport } from './routes/hegemony'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PartnerProgramRouteImport } from './routes/partner-program'
import { Route as PartnerProgrammRouteImport } from './routes/partner-programm'
import { Route as RegistrierenRouteImport } from './routes/registrieren'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as WillkommenRouteImport } from './routes/willkommen'
import { Route as SlugAdminRouteImport } from './routes/$slug_.admin'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppLessonsRouteImport } from './routes/_app.lessons'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSignalsRouteImport } from './routes/_app.signals'
import { Route as AppTierRouteImport } from './routes/_app.tier'
import { Route as AppToolsRouteImport } from './routes/_app.tools'
import { Route as AppUnlocksRouteImport } from './routes/_app.unlocks'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminDepositsRouteImport } from './routes/admin.deposits'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminLessonsRouteImport } from './routes/admin.lessons'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as AdminSignalsRouteImport } from './routes/admin.signals'
import { Route as AdminStructureRouteImport } from './routes/admin.structure'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as TSlugRouteImport } from './routes/t.$slug'
import { Route as AppLessonsIndexRouteImport } from './routes/_app.lessons.index'
import { Route as AppLessonsLessonIdRouteImport } from './routes/_app.lessons.$lessonId'

const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const HegemonyRoute = HegemonyRouteImport.update({
  id: '/hegemony',
  path: '/hegemony',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerProgramRoute = PartnerProgramRouteImport.update({
  id: '/partner-program',
  path: '/partner-program',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerProgrammRoute = PartnerProgrammRouteImport.update({
  id: '/partner-programm',
  path: '/partner-programm',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrierenRoute = RegistrierenRouteImport.update({
  id: '/registrieren',
  path: '/registrieren',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const WillkommenRoute = WillkommenRouteImport.update({
  id: '/willkommen',
  path: '/willkommen',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugAdminRoute = SlugAdminRouteImport.update({
  id: '/$slug_/admin',
  path: '/$slug/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppLessonsRoute = AppLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSignalsRoute = AppSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => AppRoute,
} as any)
const AppTierRoute = AppTierRouteImport.update({
  id: '/tier',
  path: '/tier',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsRoute = AppToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AppRoute,
} as any)
const AppUnlocksRoute = AppUnlocksRouteImport.update({
  id: '/unlocks',
  path: '/unlocks',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepositsRoute = AdminDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLessonsRoute = AdminLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSignalsRoute = AdminSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStructureRoute = AdminStructureRouteImport.update({
  id: '/structure',
  path: '/structure',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLessonsIndexRoute = AppLessonsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLessonsRoute,
} as any)
const AppLessonsLessonIdRoute = AppLessonsLessonIdRouteImport.update({
  id: '/$lessonId',
  path: '/$lessonId',
  getParentRoute: () => AppLessonsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$slug': typeof SlugRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/datenschutz': typeof DatenschutzRoute
  '/hegemony': typeof HegemonyRoute
  '/impressum': typeof ImpressumRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/partner-program': typeof PartnerProgramRoute
  '/partner-programm': typeof PartnerProgrammRoute
  '/registrieren': typeof RegistrierenRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/willkommen': typeof WillkommenRoute
  '/$slug/admin': typeof SlugAdminRoute
  '/lessons': typeof AppLessonsRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/settings': typeof AppSettingsRoute
  '/signals': typeof AppSignalsRoute
  '/tier': typeof AppTierRoute
  '/tools': typeof AppToolsRoute
  '/unlocks': typeof AppUnlocksRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/signals': typeof AdminSignalsRoute
  '/admin/structure': typeof AdminStructureRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/t/$slug': typeof TSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/lessons/$lessonId': typeof AppLessonsLessonIdRoute
  '/lessons/': typeof AppLessonsIndexRoute
}
export interface FileRoutesByTo {
  '/$slug': typeof SlugRoute
  '/datenschutz': typeof DatenschutzRoute
  '/hegemony': typeof HegemonyRoute
  '/impressum': typeof ImpressumRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/partner-program': typeof PartnerProgramRoute
  '/partner-programm': typeof PartnerProgrammRoute
  '/registrieren': typeof RegistrierenRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/willkommen': typeof WillkommenRoute
  '/$slug/admin': typeof SlugAdminRoute
  '/notifications': typeof AppNotificationsRoute
  '/settings': typeof AppSettingsRoute
  '/signals': typeof AppSignalsRoute
  '/tier': typeof AppTierRoute
  '/tools': typeof AppToolsRoute
  '/unlocks': typeof AppUnlocksRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/signals': typeof AdminSignalsRoute
  '/admin/structure': typeof AdminStructureRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/t/$slug': typeof TSlugRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/lessons/$lessonId': typeof AppLessonsLessonIdRoute
  '/lessons': typeof AppLessonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$slug': typeof SlugRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/datenschutz': typeof DatenschutzRoute
  '/hegemony': typeof HegemonyRoute
  '/impressum': typeof ImpressumRoute
  '/login': typeof LoginRoute
  '/partner': typeof PartnerRoute
  '/partner-program': typeof PartnerProgramRoute
  '/partner-programm': typeof PartnerProgrammRoute
  '/registrieren': typeof RegistrierenRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/willkommen': typeof WillkommenRoute
  '/$slug_/admin': typeof SlugAdminRoute
  '/_app/lessons': typeof AppLessonsRouteWithChildren
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/signals': typeof AppSignalsRoute
  '/_app/tier': typeof AppTierRoute
  '/_app/tools': typeof AppToolsRoute
  '/_app/unlocks': typeof AppUnlocksRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/deposits': typeof AdminDepositsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/lessons': typeof AdminLessonsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/signals': typeof AdminSignalsRoute
  '/admin/structure': typeof AdminStructureRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/t/$slug': typeof TSlugRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/lessons/$lessonId': typeof AppLessonsLessonIdRoute
  '/_app/lessons/': typeof AppLessonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$slug'
    | '/'
    | '/admin'
    | '/datenschutz'
    | '/hegemony'
    | '/impressum'
    | '/login'
    | '/partner'
    | '/partner-program'
    | '/partner-programm'
    | '/registrieren'
    | '/reset-password'
    | '/signup'
    | '/welcome'
    | '/willkommen'
    | '/$slug/admin'
    | '/lessons'
    | '/notifications'
    | '/settings'
    | '/signals'
    | '/tier'
    | '/tools'
    | '/unlocks'
    | '/admin/audit'
    | '/admin/deposits'
    | '/admin/leads'
    | '/admin/lessons'
    | '/admin/members'
    | '/admin/partners'
    | '/admin/signals'
    | '/admin/structure'
    | '/admin/support'
    | '/admin/tenants'
    | '/t/$slug'
    | '/admin/'
    | '/lessons/$lessonId'
    | '/lessons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$slug'
    | '/datenschutz'
    | '/hegemony'
    | '/impressum'
    | '/login'
    | '/partner'
    | '/partner-program'
    | '/partner-programm'
    | '/registrieren'
    | '/reset-password'
    | '/signup'
    | '/welcome'
    | '/willkommen'
    | '/$slug/admin'
    | '/notifications'
    | '/settings'
    | '/signals'
    | '/tier'
    | '/tools'
    | '/unlocks'
    | '/admin/audit'
    | '/admin/deposits'
    | '/admin/leads'
    | '/admin/lessons'
    | '/admin/members'
    | '/admin/partners'
    | '/admin/signals'
    | '/admin/structure'
    | '/admin/support'
    | '/admin/tenants'
    | '/t/$slug'
    | '/'
    | '/admin'
    | '/lessons/$lessonId'
    | '/lessons'
  id:
    | '__root__'
    | '/$slug'
    | '/_app'
    | '/admin'
    | '/datenschutz'
    | '/hegemony'
    | '/impressum'
    | '/login'
    | '/partner'
    | '/partner-program'
    | '/partner-programm'
    | '/registrieren'
    | '/reset-password'
    | '/signup'
    | '/welcome'
    | '/willkommen'
    | '/$slug_/admin'
    | '/_app/lessons'
    | '/_app/notifications'
    | '/_app/settings'
    | '/_app/signals'
    | '/_app/tier'
    | '/_app/tools'
    | '/_app/unlocks'
    | '/admin/audit'
    | '/admin/deposits'
    | '/admin/leads'
    | '/admin/lessons'
    | '/admin/members'
    | '/admin/partners'
    | '/admin/signals'
    | '/admin/structure'
    | '/admin/support'
    | '/admin/tenants'
    | '/t/$slug'
    | '/_app/'
    | '/admin/'
    | '/_app/lessons/$lessonId'
    | '/_app/lessons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SlugRoute: typeof SlugRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  DatenschutzRoute: typeof DatenschutzRoute
  HegemonyRoute: typeof HegemonyRoute
  ImpressumRoute: typeof ImpressumRoute
  LoginRoute: typeof LoginRoute
  PartnerRoute: typeof PartnerRoute
  PartnerProgramRoute: typeof PartnerProgramRoute
  PartnerProgrammRoute: typeof PartnerProgrammRoute
  RegistrierenRoute: typeof RegistrierenRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  WelcomeRoute: typeof WelcomeRoute
  WillkommenRoute: typeof WillkommenRoute
  SlugAdminRoute: typeof SlugAdminRoute
  TSlugRoute: typeof TSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hegemony': {
      id: '/hegemony'
      path: '/hegemony'
      fullPath: '/hegemony'
      preLoaderRoute: typeof HegemonyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-program': {
      id: '/partner-program'
      path: '/partner-program'
      fullPath: '/partner-program'
      preLoaderRoute: typeof PartnerProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-programm': {
      id: '/partner-programm'
      path: '/partner-programm'
      fullPath: '/partner-programm'
      preLoaderRoute: typeof PartnerProgrammRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrieren': {
      id: '/registrieren'
      path: '/registrieren'
      fullPath: '/registrieren'
      preLoaderRoute: typeof RegistrierenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/willkommen': {
      id: '/willkommen'
      path: '/willkommen'
      fullPath: '/willkommen'
      preLoaderRoute: typeof WillkommenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug_/admin': {
      id: '/$slug_/admin'
      path: '/$slug/admin'
      fullPath: '/$slug/admin'
      preLoaderRoute: typeof SlugAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lessons': {
      id: '/_app/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof AppLessonsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/signals': {
      id: '/_app/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof AppSignalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tier': {
      id: '/_app/tier'
      path: '/tier'
      fullPath: '/tier'
      preLoaderRoute: typeof AppTierRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tools': {
      id: '/_app/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AppToolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/unlocks': {
      id: '/_app/unlocks'
      path: '/unlocks'
      fullPath: '/unlocks'
      preLoaderRoute: typeof AppUnlocksRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/deposits': {
      id: '/admin/deposits'
      path: '/deposits'
      fullPath: '/admin/deposits'
      preLoaderRoute: typeof AdminDepositsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lessons': {
      id: '/admin/lessons'
      path: '/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof AdminLessonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/signals': {
      id: '/admin/signals'
      path: '/signals'
      fullPath: '/admin/signals'
      preLoaderRoute: typeof AdminSignalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/structure': {
      id: '/admin/structure'
      path: '/structure'
      fullPath: '/admin/structure'
      preLoaderRoute: typeof AdminStructureRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/lessons/': {
      id: '/_app/lessons/'
      path: '/'
      fullPath: '/lessons/'
      preLoaderRoute: typeof AppLessonsIndexRouteImport
      parentRoute: typeof AppLessonsRoute
    }
    '/_app/lessons/$lessonId': {
      id: '/_app/lessons/$lessonId'
      path: '/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof AppLessonsLessonIdRouteImport
      parentRoute: typeof AppLessonsRoute
    }
  }
}

interface AppLessonsRouteChildren {
  AppLessonsLessonIdRoute: typeof AppLessonsLessonIdRoute
  AppLessonsIndexRoute: typeof AppLessonsIndexRoute
}

const AppLessonsRouteChildren: AppLessonsRouteChildren = {
  AppLessonsLessonIdRoute: AppLessonsLessonIdRoute,
  AppLessonsIndexRoute: AppLessonsIndexRoute,
}

const AppLessonsRouteWithChildren = AppLessonsRoute._addFileChildren(
  AppLessonsRouteChildren,
)

interface AppRouteChildren {
  AppLessonsRoute: typeof AppLessonsRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSignalsRoute: typeof AppSignalsRoute
  AppTierRoute: typeof AppTierRoute
  AppToolsRoute: typeof AppToolsRoute
  AppUnlocksRoute: typeof AppUnlocksRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLessonsRoute: AppLessonsRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSignalsRoute: AppSignalsRoute,
  AppTierRoute: AppTierRoute,
  AppToolsRoute: AppToolsRoute,
  AppUnlocksRoute: AppUnlocksRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDepositsRoute: typeof AdminDepositsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLessonsRoute: typeof AdminLessonsRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminSignalsRoute: typeof AdminSignalsRoute
  AdminStructureRoute: typeof AdminStructureRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminDepositsRoute: AdminDepositsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLessonsRoute: AdminLessonsRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminSignalsRoute: AdminSignalsRoute,
  AdminStructureRoute: AdminStructureRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SlugRoute: SlugRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  DatenschutzRoute: DatenschutzRoute,
  HegemonyRoute: HegemonyRoute,
  ImpressumRoute: ImpressumRoute,
  LoginRoute: LoginRoute,
  PartnerRoute: PartnerRoute,
  PartnerProgramRoute: PartnerProgramRoute,
  PartnerProgrammRoute: PartnerProgrammRoute,
  RegistrierenRoute: RegistrierenRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  WelcomeRoute: WelcomeRoute,
  WillkommenRoute: WillkommenRoute,
  SlugAdminRoute: SlugAdminRoute,
  TSlugRoute: TSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
